base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: r3dsonia
  
development:
  database: victoria_development
  socket: /tmp/mysql.sock
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: 1x2Ekwals2

staging:
  database: victoria_staging
  socket: /var/run/mysqld/mysqld.sock
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: r3dsonia

test:
  database: victoria_test
  socket: /tmp/mysql.sock
  <<: *base
  
production:
  database: victoria_production
  socket: /var/run/mysqld/mysqld.sock
  <<: *base
  
  # Or@ng3$od@